# {{PROJECT_NAME}} - Environment Configuration
# Genererat av Nexus RAG Builder v1.0

# === LLM Configuration (Google Gemini) ===
GOOGLE_API_KEY={{GOOGLE_API_KEY}}
GEMINI_EMBEDDING_MODEL={{GEMINI_EMBEDDING_MODEL}}
GEMINI_GENERATION_MODEL={{GEMINI_GENERATION_MODEL}}
EMBEDDING_DIMENSION={{EMBEDDING_DIMENSION}}

# === Supabase (Database & Auth) ===
SUPABASE_URL={{SUPABASE_URL}}
SUPABASE_SERVICE_ROLE_KEY={{SUPABASE_SERVICE_ROLE_KEY}}

# === Qdrant (Vector Database) ===
QDRANT_HOST={{QDRANT_HOST}}
QDRANT_PORT={{QDRANT_PORT}}

# === Redis (Cache) ===
REDIS_HOST={{REDIS_HOST}}
REDIS_PASSWORD={{REDIS_PASSWORD}}

# === Application Settings ===
APP_PORT={{APP_PORT}}
SEARCH_TOP_K={{SEARCH_TOP_K}}
RELEVANCE_THRESHOLD={{RELEVANCE_THRESHOLD}}

# === Projekt Metadata ===
PROJECT_DESCRIPTION="{{PROJECT_DESCRIPTION}}"